<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SimpleSoftwareIO\\QrCode\\' => array($vendorDir . '/simplesoftwareio/simple-qrcode/src'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Milon\\Barcode' => array($vendorDir . '/milon/barcode/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Folklore\\Image\\Tests' => array($vendorDir . '/folklore/image/tests'),
    'Folklore\\Image\\' => array($vendorDir . '/folklore/image/src'),
    'BaconQrCode' => array($vendorDir . '/bacon/bacon-qr-code/src'),
);
